# Required to run your project under the correct environment.
language: php

# Versions of PHP you want your project run with.
php:
  - 5.6
  - 7.1
  - hhvm

before_install:
  - echo "Running BeforeInstall"
  - docker-compose up -d

# Commands to be run before your environment runs.
before_script:
  - echo "Running BeforeScript"
  - composer self-update
  - composer install --prefer-source --no-interaction

# Commands you want to run that will verify your build.
script:
  - echo "RunningScript"
  - docker exec test-fpm ./bin/kahlan --cc=true --src=src --spec=spec/suite --reporter=verbose --coverage=4 --clover=clover.xml

after_success:
  - echo "Running AfterSuccess"

after_script:
  - echo "Running AfterScript"
  - php ./bin/codacycoverage clover clover.xml

# allow_failures: Allow this build to fail under the specified environments.
# fast_finish: If your build fails do not continue trying to build, just stop.
matrix:
  allow_failures:
    - php: 7.1
    - php: hhvm
  fast_finish: true

# Customize when the notification emails are sent.
notifications:
    on_success: never
    on_failure: always

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

services:
  - docker
