# Required to run your project under the correct environment.
language: php

# Versions of PHP you want your project run with.
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

before_install:
  - echo "Running BeforeInstall"
  - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini


# Commands to be run before your environment runs.
before_script:
  - echo "Running BeforeScript"
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

# Commands you want to run that will verify your build.
script:
  - echo "RunningScript"
  - bin/kahlan --cc=true --reporter=verbose

after_success:
  - echo "Running AfterSuccess"

# allow_failures: Allow this build to fail under the specified environments.
# fast_finish: If your build fails do not continue trying to build, just stop.
matrix:
  allow_failures:
    - php: 5.4
    - php: 5.5
    - php: 7.0
    - php: 7.1
    - php: hhvm
  fast_finish: true

# Customize when the notification emails are sent.
notifications:
    on_success: never
    on_failure: always

cache:
  directories:
    - $HOME/.composer/cache

services:
  - mongo
